CREATE DATABASE test;
GRANT ALL PRIVILEGES ON DATABASE test TO accounts;
CREATE DATABASE keys_test;
GRANT ALL PRIVILEGES ON DATABASE test TO accounts;
CREATE DATABASE keys;
GRANT ALL PRIVILEGES ON DATABASE keys TO accounts;
