networks:
  main:

services:
  postgres:
    build:
      dockerfile: pg.Dockerfile
    ports:
      - "5435:5432"
    networks:
      - main
    command: ["postgres", "-c", "shared_preload_libraries=pg_cron"]
    environment:
      - POSTGRES_USER=accounts
      - POSTGRES_PASSWORD=password
    volumes:
      - ./misc/create_additional_dbs.sql:/docker-entrypoint-initdb.d/create_additional_dbs.sql
  ses-local:
    build:
      context: ./misc/ses-v2-local
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:4566:4566"
    networks:
      - main
  app:
    build: .
    networks:
      - main
    env_file: .env
    environment:
      DATABASE_URL: postgres://accounts:password@postgres:5432/postgres?sslmode=disable
      AWS_ENDPOINT: http://ses-local:4566
    depends_on:
      - postgres
      - ses-local
    restart: on-failure
    ports:
      - "127.0.0.1:8080:8080"
