DROP TABLE pending_webhook_events;
DROP TABLE user_keys;
DROP TABLE verifications;
DROP TABLE sessions;
DROP TABLE registration_states;
DROP TABLE ake_states;
DROP TABLE accounts;
DROP TABLE jwt_keys;
DROP TABLE oprf_seeds;
