CREATE TABLE totp_keys (
    account_id UUID PRIMARY KEY,
    key TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE accounts ADD COLUMN totp_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE accounts ADD COLUMN recovery_key_hash BYTEA;

ALTER TABLE ake_states RENAME TO login_states;
ALTER TABLE login_states ADD COLUMN awaiting_twofa BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE login_states ADD COLUMN requires_twofa BOOLEAN NOT NULL DEFAULT FALSE;