[VerifyEmailSubject]
description = "Email subject for email verification"
other = "Verify your email"

[SetPasswordEmailSubject]
description = "Email subject for setting a new password"
other = "Set a new password for your Brave account"

[RegistrationEmailSubject]
description = "Email subject for creating a new account"
other = "Create your Brave account"

[LoginEmailSubject]
description = "Email subject for logging into an account"
other = "Access your Brave account"

[EmailGreeting]
description = "Greeting in the email message"
other = "Hello,"

[SetPasswordEmailInstructions]
description = "Instructions to verify email address and set a new password for an account"
other = "Click the link below to verify your email and set a new password for your account. (You can also paste the link in your browser.) Note that this email contains a private access link that can only be used once."

[RegistrationEmailInstructions]
description = "Instructions to verify email address and create a new account"
other = "Click the link below to verify your email and create your Brave account. (You can also paste the link in your browser.) Note that this email contains a private access link that can only be used once."

[VerifyEmailInstructions]
description = "Instructions to verify email address"
other = "Click the link below to verify your email. (You can also paste the link in your browser.) Note that this email contains a private access link that can only be used once."

[LoginEmailInstructions]
description = "Instruction to verify an email address and login to an account"
other = "Click the link below to access your Brave account. (You can also paste the link in your browser.) Note that this email contains a private access link that can only be used once."

[VerifyEmailAction]
description = "Text on the email verification button"
other = "Confirm your email"

[VerifyEmailShortAction]
description = "Text on the inbox action button for email verification"
other = "Confirm"

[VerifyEmailActionBackup]
description = "Instructions for manual link usage if button doesn't work"
other = "Don’t see a button? Click this link to confirm your email."

[VerifyEmailExpiryDisclaimer]
description = "Informs the user that the link expires after 30 minutes"
other = "Note: This confirmation prompt will expire within 30 minutes."

[SimilarEmailLoginMessage]
description = "Informs the user that an account exists with a similar email address after an unsuccessful login attempt"
other = "We noticed you're having trouble logging into your Brave Account. Please remember that you have an account registered with this email: {{.Email}}\n\nTry logging in using this email address. If you still need help, please contact our support team."

[SimilarEmailSubject]
description = "Subject for informing the user that an account exists with a similar email address after an unsuccessful login attempt"
other = "Having trouble? Here's how to access your Brave Account"

[EmailSignature]
description = "Email signature"
other = "The Brave Team"

[EmailDisregard]
description = "Instructs the user to ignore the email if the user did not initiate the verification or login request"
other = "If you didn’t make this request, please disregard this email."

[EmailCopyright]
description = "Brave copyright notice"
other = "Copyright © {{.Year}} Brave Software Inc."

[EmailAllRightsReserved]
description = "All rights reserved notice"
other = "All rights reserved"

[EmailPrivacyPolicy]
description = "Privacy policy link text"
other = "Privacy Policy"

[EmailTermsOfUse]
description = "Terms of use link text"
other = "Terms of Use"

[EmailDownloadBrave]
description = "Brave download link text"
other = "Download Brave"

[EmailContactSupport]
description = "Support contact link text"
other = "Contact Support"

[PasswordChangeNotificationSubject]
description = "Email subject for password change notification"
other = "Your Brave account password has been changed"

[PasswordChangeNotificationMessage]
description = "Email message informing user that their password was changed"
other = "Your Brave account password has been successfully changed. If you didn't make this change, please contact our support team immediately to secure your account."
