[VerifyEmailSubject]
description = "Email subject for email verification"
other = "I-verify ang email mo"

[SetPasswordEmailSubject]
description = "Email subject for setting a new password"
other = "Mag-set ng bagong password para sa Brave account mo"

[RegistrationEmailSubject]
description = "Email subject for creating a new account"
other = "Gawin ang Brave account mo"

[EmailGreeting]
description = "Greeting in the email message"
other = "Hello,"

[SetPasswordEmailInstructions]
description = "Instructions to verify email address and set a new password for an account"
other = "Heto ang code na kakailanganin mo para i-verify ang iyong email address at mag-set ng bagong password para sa Brave account mo."

[RegistrationEmailInstructions]
description = "Instructions to verify email address and create a new account"
other = "Heto ang code na kakailanganin mo para i-verify ang iyong email address at gawin ang Brave account mo."

[VerifyEmailInstructions]
description = "Instructions to verify email address"
other = "Heto ang code na kakailanganin mo para i-verify ang iyong email address."

[VerifyEmailCode]
description = "Label preceding the verification code displayed in the email"
other = "Ang iyong verification code:"

[VerifyEmailExpiryDisclaimer]
description = "Informs the user how many minutes until the verification code expires"
other = "Tandaan: Mag-e-expire ang code sa loob ng {{.Minutes}} (na) minuto."

[SimilarEmailLoginMessage]
description = "Informs the user that an account exists with a similar email address after an unsuccessful login attempt"
other = """
Parang may account ka na na naka-register gamit ang email na ito: {{.Email}}.

Subukang mag-log in gamit ang email address na ito. Kung kailangan mo pa rin ng tulong, pakikontak ang Brave support."""

[SimilarEmailSubject]
description = "Subject for informing the user that an account exists with a similar email address after an unsuccessful login attempt"
other = "Nagkakaproblema? Ganito ang gawin mo para ma-access ang iyong Brave Account."

[EmailSignature]
description = "Email signature"
other = "Ang Brave Team"

[EmailDisregard]
description = "Instructs the user to ignore the email if the user did not initiate the verification or login request"
other = "Kung hindi mo ginawa ang request na ito, balewalain ang email na ito."

[EmailCopyright]
description = "Brave copyright notice"
other = "Copyright © {{.Year}} Brave Software Inc."

[EmailAllRightsReserved]
description = "All rights reserved notice"
other = "All rights reserved"

[EmailPrivacyPolicy]
description = "Privacy policy link text"
other = "Patakaran sa Privacy"

[EmailTermsOfUse]
description = "Terms of use link text"
other = "Mga Tuntunin sa Paggamit"

[EmailDownloadBrave]
description = "Brave download link text"
other = "I-download ang Brave"

[EmailContactSupport]
description = "Support contact link text"
other = "Kontakin ang Support"

[PasswordChangeNotificationSubject]
description = "Email subject for password change notification"
other = "Nabago ang password ng Brave account mo"

[PasswordChangeNotificationMessage]
description = "Email message informing user that their password was changed"
other = "Nabago ang password ng Brave account mo. Kung hindi mo ito binago, pakikontak ang Brave support kaagad-agad para ma-secure ang account mo."

[PasswordChangeNotificationDisregard]
description = "Footer for password change notification email reassuring the user if they made the change"
other = "If you did make this change, no further action is required."
