[VerifyEmailSubject]
description = "Email subject for email verification"
other = "이메일 인증"

[SetPasswordEmailSubject]
description = "Email subject for setting a new password"
other = "Brave 계정의 새 비밀번호 설정"

[RegistrationEmailSubject]
description = "Email subject for creating a new account"
other = "Brave 계정 만들기"

[EmailGreeting]
description = "Greeting in the email message"
other = "안녕하세요."

[SetPasswordEmailInstructions]
description = "Instructions to verify email address and set a new password for an account"
other = "다음은 이메일 주소를 인증하고 Brave 계정의 새 비밀번호를 설정하는 데 필요한 코드입니다."

[RegistrationEmailInstructions]
description = "Instructions to verify email address and create a new account"
other = "다음은 이메일 주소를 인증하고 Brave 계정을 생성하는 데 필요한 코드입니다."

[VerifyEmailInstructions]
description = "Instructions to verify email address"
other = "다음은 이메일 주소를 인증하는 데 필요한 코드입니다."

[VerifyEmailCode]
description = "Label preceding the verification code displayed in the email"
other = "내 인증 코드:"

[VerifyEmailExpiryDisclaimer]
description = "Informs the user how many minutes until the verification code expires"
other = "참고: 이 코드는 {{.Minutes}}분 후에 만료됩니다."

[SimilarEmailLoginMessage]
description = "Informs the user that an account exists with a similar email address after an unsuccessful login attempt"
other = """
{{.Email}} 이메일에 이미 등록된 계정이 있는 것 같습니다.

이 이메일 주소로 로그인해 보세요. 그래도 도움이 필요하면 Brave 지원팀에 문의하세요."""

[SimilarEmailSubject]
description = "Subject for informing the user that an account exists with a similar email address after an unsuccessful login attempt"
other = "문제가 있나요? Brave 계정에 액세스하는 방법은 다음과 같습니다."

[EmailSignature]
description = "Email signature"
other = "Brave 팀"

[EmailDisregard]
description = "Instructs the user to ignore the email if the user did not initiate the verification or login request"
other = "이 요청을 하지 않았다면 이 이메일은 무시해 주세요."

[EmailCopyright]
description = "Brave copyright notice"
other = "Copyright © {{.Year}} Brave Software Inc."

[EmailAllRightsReserved]
description = "All rights reserved notice"
other = "All rights reserved"

[EmailPrivacyPolicy]
description = "Privacy policy link text"
other = "개인정보 보호정책"

[EmailTermsOfUse]
description = "Terms of use link text"
other = "이용 약관"

[EmailDownloadBrave]
description = "Brave download link text"
other = "Brave 다운로드"

[EmailContactSupport]
description = "Support contact link text"
other = "지원팀에 문의"

[PasswordChangeNotificationSubject]
description = "Email subject for password change notification"
other = "Brave 계정 비밀번호 변경 완료"

[PasswordChangeNotificationMessage]
description = "Email message informing user that their password was changed"
other = "Brave 계정 비밀번호를 변경했습니다. 비밀번호를 변경하지 않은 경우 즉시 Brave 지원팀에 문의하여 계정을 보호하세요."

[PasswordChangeNotificationDisregard]
description = "Footer for password change notification email reassuring the user if they made the change"
other = "If you did make this change, no further action is required."
