[VerifyEmailSubject]
description = "Email subject for email verification"
other = "Confirmar seu email"

[SetPasswordEmailSubject]
description = "Email subject for setting a new password"
other = "Definir uma nova senha para sua conta Brave"

[RegistrationEmailSubject]
description = "Email subject for creating a new account"
other = "Crie sua conta Brave"

[EmailGreeting]
description = "Greeting in the email message"
other = "Olá,"

[SetPasswordEmailInstructions]
description = "Instructions to verify email address and set a new password for an account"
other = "Aqui está o código que você precisará para confirmar seu endereço de e-mail e definir uma nova senha para sua conta Brave."

[RegistrationEmailInstructions]
description = "Instructions to verify email address and create a new account"
other = "Aqui está o código que você precisará para confirmar seu endereço de e-mail e criar sua conta Brave."

[VerifyEmailInstructions]
description = "Instructions to verify email address"
other = "Aqui está o código que você precisará para confirmar seu endereço de e-mail."

[VerifyEmailCode]
description = "Label preceding the verification code displayed in the email"
other = "Seu código de verificação:"

[VerifyEmailExpiryDisclaimer]
description = "Informs the user how many minutes until the verification code expires"
other = "Observação: Esse código expirará em {{.Minutes}} minutos."

[SimilarEmailLoginMessage]
description = "Informs the user that an account exists with a similar email address after an unsuccessful login attempt"
other = """
Parece que você já possui uma conta cadastrada com este e-mail: {{.Email}}.

Tente fazer o login usando este endereço de e-mail. Caso ainda necessite de ajuda, entre em contato com o suporte Brave."""

[SimilarEmailSubject]
description = "Subject for informing the user that an account exists with a similar email address after an unsuccessful login attempt"
other = "Está tendo dificuldades? Veja aqui como acessar a sua conta Brave."

[EmailSignature]
description = "Email signature"
other = "Equipe Brave"

[EmailDisregard]
description = "Instructs the user to ignore the email if the user did not initiate the verification or login request"
other = "Caso você não tenha feito essa solicitação, desconsidere este e-mail."

[EmailCopyright]
description = "Brave copyright notice"
other = "Copyright © {{.Year}} Brave Software Inc."

[EmailAllRightsReserved]
description = "All rights reserved notice"
other = "Todos os direitos reservados"

[EmailPrivacyPolicy]
description = "Privacy policy link text"
other = "Política de Privacidade"

[EmailTermsOfUse]
description = "Terms of use link text"
other = "Termos de Uso"

[EmailDownloadBrave]
description = "Brave download link text"
other = "Baixar o Brave"

[EmailContactSupport]
description = "Support contact link text"
other = "Entre em contato com o suporte"

[PasswordChangeNotificationSubject]
description = "Email subject for password change notification"
other = "A senha de sua conta Brave foi alterada"

[PasswordChangeNotificationMessage]
description = "Email message informing user that their password was changed"
other = "A senha de sua conta Brave foi alterada. Caso você não tenha feito essa alteração, entre em contato com o suporte Brave imediatamente para garantira a segurança de sua conta."

[PasswordChangeNotificationDisregard]
description = "Footer for password change notification email reassuring the user if they made the change"
other = "If you did make this change, no further action is required."
