[VerifyEmailSubject]
description = "Email subject for email verification"
other = "Verifiera din e-postadress"

[SetPasswordEmailSubject]
description = "Email subject for setting a new password"
other = "Ange ett nytt lösenord för ditt Brave-konto"

[RegistrationEmailSubject]
description = "Email subject for creating a new account"
other = "Skapa ditt Brave-konto"

[EmailGreeting]
description = "Greeting in the email message"
other = "Hej,"

[SetPasswordEmailInstructions]
description = "Instructions to verify email address and set a new password for an account"
other = "Här är koden som du behöver för att verifiera din e-postadress och ange ett nytt lösenord för ditt Brave-konto."

[RegistrationEmailInstructions]
description = "Instructions to verify email address and create a new account"
other = "Här är koden som du behöver för att verifiera din e-postadress och skapa ditt Brave-konto."

[VerifyEmailInstructions]
description = "Instructions to verify email address"
other = "Här är koden som du behöver för att verifiera din e-postadress."

[VerifyEmailCode]
description = "Label preceding the verification code displayed in the email"
other = "Din verifieringskod:"

[VerifyEmailExpiryDisclaimer]
description = "Informs the user how many minutes until the verification code expires"
other = "Obs: Den här koden upphör att gälla om {{.Minutes}} minuter."

[SimilarEmailLoginMessage]
description = "Informs the user that an account exists with a similar email address after an unsuccessful login attempt"
other = """
Det verkar som om du redan har ett konto registrerat med den här e-postadressen: {{.Email}}.

Försök att logga in med den e-postadressen. Om du fortfarande behöver hjälp, vänligen kontakta Brave-support."""

[SimilarEmailSubject]
description = "Subject for informing the user that an account exists with a similar email address after an unsuccessful login attempt"
other = "Behöver du hjälp? Så här får du tillgång till ditt Brave-konto."

[EmailSignature]
description = "Email signature"
other = "Brave-teamet"

[EmailDisregard]
description = "Instructs the user to ignore the email if the user did not initiate the verification or login request"
other = "Om du inte har gjort denna begäran kan du bortse från detta meddelande."

[EmailCopyright]
description = "Brave copyright notice"
other = "Copyright ©️ {{.Year}} Brave Software Inc."

[EmailAllRightsReserved]
description = "All rights reserved notice"
other = "Alla rättigheter förbehållna"

[EmailPrivacyPolicy]
description = "Privacy policy link text"
other = "Integritetspolicy"

[EmailTermsOfUse]
description = "Terms of use link text"
other = "Användarvillkor"

[EmailDownloadBrave]
description = "Brave download link text"
other = "Ladda ner Brave"

[EmailContactSupport]
description = "Support contact link text"
other = "Kontakta support"

[PasswordChangeNotificationSubject]
description = "Email subject for password change notification"
other = "Lösenordet för ditt Brave-konto har ändrats"

[PasswordChangeNotificationMessage]
description = "Email message informing user that their password was changed"
other = "Lösenordet för ditt Brave-konto har ändrats. Om du inte har gjort den här ändringen bör du kontakta Braves support omgående för att skydda ditt konto."
