[VerifyEmailSubject]
description = "Email subject for email verification"
other = "验证您的电子邮件地址"

[SetPasswordEmailSubject]
description = "Email subject for setting a new password"
other = "为您的 Brave 账户设置一个新密码"

[RegistrationEmailSubject]
description = "Email subject for creating a new account"
other = "创建您的 Brave 账户"

[LoginEmailSubject]
description = "Email subject for logging into an account"
other = "访问您的 Brave 账户"

[EmailGreeting]
description = "Greeting in the email message"
other = "您好，"

[SetPasswordEmailInstructions]
description = "Instructions to verify email address and set a new password for an account"
other = "这是您验证电子邮件地址和为 Brave 账户设置新密码所需的验证码。"

[RegistrationEmailInstructions]
description = "Instructions to verify email address and create a new account"
other = "这是您验证电子邮件地址和创建 Brave 账户所需的验证码。"

[VerifyEmailInstructions]
description = "Instructions to verify email address"
other = "这是您验证电子邮件地址所需的验证码。"

[LoginEmailInstructions]
description = "Instruction to verify an email address and login to an account"
other = "这是您访问 Brave 账户所需的验证码。"

[VerifyEmailCode]
description = "Label preceding the verification code displayed in the email"
other = "您的验证码："

[VerifyEmailExpiryDisclaimer]
description = "Informs the user how many minutes until the verification code expires"
other = "注意：此验证码将会在 {{.Minutes}} 后失效。"

[SimilarEmailLoginMessage]
description = "Informs the user that an account exists with a similar email address after an unsuccessful login attempt"
other = """
您似乎已有一个使用 {{.Email}} 注册的账户。

请尝试使用该电子邮件地址登录账户。如果您仍需要帮助，请联系 Brave 客户支持。"""

[SimilarEmailSubject]
description = "Subject for informing the user that an account exists with a similar email address after an unsuccessful login attempt"
other = "遇到了问题？以下是访问您的 Brave 账户的方法。"

[EmailSignature]
description = "Email signature"
other = "Brave 团队"

[EmailDisregard]
description = "Instructs the user to ignore the email if the user did not initiate the verification or login request"
other = "如果您没有提出此请求，请忽略此电子邮件。"

[EmailCopyright]
description = "Brave copyright notice"
other = "Copyright © {{.Year}} Brave Software Inc。"

[EmailAllRightsReserved]
description = "All rights reserved notice"
other = "保留所有权利"

[EmailPrivacyPolicy]
description = "Privacy policy link text"
other = "隐私政策"

[EmailTermsOfUse]
description = "Terms of use link text"
other = "使用条款"

[EmailDownloadBrave]
description = "Brave download link text"
other = "下载 Brave"

[EmailContactSupport]
description = "Support contact link text"
other = "联系客户支持"

[PasswordChangeNotificationSubject]
description = "Email subject for password change notification"
other = "您的 Brave 账户密码已更改"

[PasswordChangeNotificationMessage]
description = "Email message informing user that their password was changed"
other = "您的 Brave 账户密码已成功更改。如果您没有更改密码，请立即联系 Brave 支持人员，以确保您的账户安全。"
